// <auto-generated/>
#pragma warning disable CS0618
using ApiClient.Models;
using ApiClient.Products.Item.Dimensions;
using ApiClient.Products.Item.Disable;
using ApiClient.Products.Item.Enable;
using ApiClient.Products.Item.LeadTime;
using ApiClient.Products.Item.Name;
using ApiClient.Products.Item.StockThreshold;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiClient.Products.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \products\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The dimensions property</summary>
        public global::ApiClient.Products.Item.Dimensions.DimensionsRequestBuilder Dimensions
        {
            get => new global::ApiClient.Products.Item.Dimensions.DimensionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The disable property</summary>
        public global::ApiClient.Products.Item.Disable.DisableRequestBuilder Disable
        {
            get => new global::ApiClient.Products.Item.Disable.DisableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The enable property</summary>
        public global::ApiClient.Products.Item.Enable.EnableRequestBuilder Enable
        {
            get => new global::ApiClient.Products.Item.Enable.EnableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The leadTime property</summary>
        public global::ApiClient.Products.Item.LeadTime.LeadTimeRequestBuilder LeadTime
        {
            get => new global::ApiClient.Products.Item.LeadTime.LeadTimeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The name property</summary>
        public global::ApiClient.Products.Item.Name.NameRequestBuilder Name
        {
            get => new global::ApiClient.Products.Item.Name.NameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stockThreshold property</summary>
        public global::ApiClient.Products.Item.StockThreshold.StockThresholdRequestBuilder StockThreshold
        {
            get => new global::ApiClient.Products.Item.StockThreshold.StockThresholdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiClient.Products.Item.ProductsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/products/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiClient.Products.Item.ProductsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/products/{id}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::ApiClient.Models.ProductModel"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiClient.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::ApiClient.Models.ProblemDetails">When receiving a 404 status code</exception>
        /// <exception cref="global::ApiClient.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiClient.Models.ProductModel?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiClient.Models.ProductModel> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::ApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "404", global::ApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::ApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ApiClient.Models.ProductModel>(requestInfo, global::ApiClient.Models.ProductModel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::ApiClient.Models.ProductModel"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::ApiClient.Models.ProblemDetails">When receiving a 404 status code</exception>
        /// <exception cref="global::ApiClient.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiClient.Models.ProductModel?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiClient.Models.ProductModel> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::ApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::ApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::ApiClient.Models.ProductModel>(requestInfo, global::ApiClient.Models.ProductModel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiClient.Products.Item.ProductsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiClient.Products.Item.ProductsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ApiClient.Products.Item.ProductsItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
