// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProductModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdOn property</summary>
        public DateTimeOffset? CreatedOn { get; set; }
        /// <summary>The dimensions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::ApiClient.Models.NullableOfProductDimensions? Dimensions { get; set; }
#nullable restore
#else
        public global::ApiClient.Models.NullableOfProductDimensions Dimensions { get; set; }
#endif
        /// <summary>The inventoryId property</summary>
        public Guid? InventoryId { get; set; }
        /// <summary>The isAvailable property</summary>
        public bool? IsAvailable { get; set; }
        /// <summary>The isEnabled property</summary>
        public bool? IsEnabled { get; set; }
        /// <summary>The isStocked property</summary>
        public bool? IsStocked { get; set; }
        /// <summary>The leadTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LeadTime { get; set; }
#nullable restore
#else
        public string LeadTime { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The productId property</summary>
        public Guid? ProductId { get; set; }
        /// <summary>The quantity property</summary>
        public int? Quantity { get; set; }
        /// <summary>The sku property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sku { get; set; }
#nullable restore
#else
        public string Sku { get; set; }
#endif
        /// <summary>The stockThreshold property</summary>
        public int? StockThreshold { get; set; }
        /// <summary>The updatedOn property</summary>
        public DateTimeOffset? UpdatedOn { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiClient.Models.ProductModel"/> and sets the default values.
        /// </summary>
        public ProductModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiClient.Models.ProductModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiClient.Models.ProductModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiClient.Models.ProductModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdOn", n => { CreatedOn = n.GetDateTimeOffsetValue(); } },
                { "dimensions", n => { Dimensions = n.GetObjectValue<global::ApiClient.Models.NullableOfProductDimensions>(global::ApiClient.Models.NullableOfProductDimensions.CreateFromDiscriminatorValue); } },
                { "inventoryId", n => { InventoryId = n.GetGuidValue(); } },
                { "isAvailable", n => { IsAvailable = n.GetBoolValue(); } },
                { "isEnabled", n => { IsEnabled = n.GetBoolValue(); } },
                { "isStocked", n => { IsStocked = n.GetBoolValue(); } },
                { "leadTime", n => { LeadTime = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "productId", n => { ProductId = n.GetGuidValue(); } },
                { "quantity", n => { Quantity = n.GetIntValue(); } },
                { "sku", n => { Sku = n.GetStringValue(); } },
                { "stockThreshold", n => { StockThreshold = n.GetIntValue(); } },
                { "updatedOn", n => { UpdatedOn = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdOn", CreatedOn);
            writer.WriteObjectValue<global::ApiClient.Models.NullableOfProductDimensions>("dimensions", Dimensions);
            writer.WriteGuidValue("inventoryId", InventoryId);
            writer.WriteBoolValue("isAvailable", IsAvailable);
            writer.WriteBoolValue("isEnabled", IsEnabled);
            writer.WriteBoolValue("isStocked", IsStocked);
            writer.WriteStringValue("leadTime", LeadTime);
            writer.WriteStringValue("name", Name);
            writer.WriteGuidValue("productId", ProductId);
            writer.WriteIntValue("quantity", Quantity);
            writer.WriteStringValue("sku", Sku);
            writer.WriteIntValue("stockThreshold", StockThreshold);
            writer.WriteDateTimeOffsetValue("updatedOn", UpdatedOn);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
